import { InsuranceService } from "@/types";

export const LIABILITY_PRODUCTS: InsuranceService[] = [
  {
    id: "contractors-all-risk",
    title: "Contractors All Risk",
    slug: "contractors-all-risk",
    category: "liability",
    shortDescription:
      "Comprehensive cover for construction projects — materials, plant, equipment, and third-party liability.",
    description:
      "Designed for contractors and developers, this policy covers construction works, temporary structures, construction plant and equipment, and third-party liability arising from construction activities. Ideal for building, civil engineering, and infrastructure projects.",
    icon: "HardHat",
    targetAudience:
      "Construction companies, contractors, developers, project managers",
    popular: true,
    features: [
      "Cover for contract works and materials",
      "Construction plant and equipment",
      "Third-party property damage liability",
      "Personal injury to third parties",
      "Debris removal after an incident",
      "Professional fees for reconstruction",
      "Accelerated freight costs",
    ],
    premium: [
      {
        id: "car-1",
        name: "Contract Value up to KES 10M",
        amount: 75000,
        period: "annually",
        description: "0.75% of contract value",
      },
      {
        id: "car-2",
        name: "Contract Value up to KES 50M",
        amount: 325000,
        period: "annually",
        description: "0.65% of contract value",
      },
      {
        id: "car-3",
        name: "Contract Value up to KES 100M",
        amount: 550000,
        period: "annually",
        description: "0.55% of contract value",
      },
      {
        id: "car-4",
        name: "Contract Value above KES 100M",
        amount: 0.5,
        period: "annually",
        description: "0.5% of contract value - call for custom quote",
      },
    ],
  },
  {
    id: "cyber-liability",
    title: "Cyber Liability",
    slug: "cyber-liability",
    category: "liability",
    shortDescription:
      "Protection against data breaches, cyber attacks, and regulatory fines.",
    description:
      "In today's digital economy, cyber threats are a reality. This policy covers your business against the cost of data breaches, ransomware attacks, business interruption from system failures, and regulatory fines for non-compliance.",
    icon: "Shield",
    targetAudience:
      "Any business with digital assets, customer data, or online operations",
    features: [
      "Data breach response costs",
      "Ransomware and extortion cover",
      "Business interruption from cyber events",
      "Regulatory fines and penalties",
      "PR and crisis management costs",
      "Forensic investigation fees",
      "Data restoration costs",
    ],
    premium: [
      {
        id: "cyber-1",
        name: "Small Business (1-10 employees)",
        amount: 25000,
        period: "annually",
        description: "Up to KES 5M cover",
      },
      {
        id: "cyber-2",
        name: "Medium Business (11-50 employees)",
        amount: 65000,
        period: "annually",
        description: "Up to KES 15M cover",
      },
      {
        id: "cyber-3",
        name: "Large Business (51-200 employees)",
        amount: 150000,
        period: "annually",
        description: "Up to KES 30M cover",
      },
      {
        id: "cyber-4",
        name: "Enterprise (200+ employees)",
        amount: 350000,
        period: "annually",
        description: "Custom cover limits available",
      },
    ],
  },
  {
    id: "commercial-crime",
    title: "Commercial Crime",
    slug: "commercial-crime",
    category: "liability",
    shortDescription:
      "Cover for employee dishonesty, theft of money, forgery, and computer fraud.",
    description:
      "Protect your business from financial losses resulting from criminal acts by employees or third parties. This policy covers theft of money and securities, forgery, computer fraud, and funds transfer fraud.",
    icon: "Landmark",
    targetAudience:
      "Businesses handling cash, securities, or sensitive financial data",
    features: [
      "Employee dishonesty and fraud",
      "Theft of money and securities",
      "Forgery or alteration of instruments",
      "Computer and funds transfer fraud",
      "Robbery and safe burglary",
      "Courier and transit cover",
    ],
    premium: [
      {
        id: "crime-1",
        name: "Cover up to KES 1M",
        amount: 15000,
        period: "annually",
        description: "For small retail or office",
      },
      {
        id: "crime-2",
        name: "Cover up to KES 5M",
        amount: 55000,
        period: "annually",
        description: "For medium businesses",
      },
      {
        id: "crime-3",
        name: "Cover up to KES 10M",
        amount: 95000,
        period: "annually",
        description: "For larger operations",
      },
      {
        id: "crime-4",
        name: "Cover up to KES 25M",
        amount: 195000,
        period: "annually",
        description: "For enterprises with high cash handling",
      },
    ],
  },
  {
    id: "directors-officers",
    title: "Directors & Officers Liability",
    slug: "directors-officers",
    category: "liability",
    shortDescription:
      "Personal protection for company directors and officers against legal claims.",
    description:
      "Directors and officers face increasing personal liability for decisions made on behalf of the company. This policy covers legal costs and damages arising from alleged wrongful acts, breaches of duty, mismanagement, or regulatory investigations.",
    icon: "Briefcase",
    targetAudience:
      "Public and private companies, non-profits, board members, executives",
    features: [
      "Defence costs for legal proceedings",
      "Settlements and damages",
      "Regulatory investigation cover",
      "Employment practices liability",
      "Coverage for former directors",
      "Spousal coverage extension",
    ],
    premium: [
      {
        id: "do-1",
        name: "Small Company (up to KES 100M revenue)",
        amount: 85000,
        period: "annually",
        description: "Up to KES 20M cover",
      },
      {
        id: "do-2",
        name: "Medium Company (KES 100-500M revenue)",
        amount: 185000,
        period: "annually",
        description: "Up to KES 50M cover",
      },
      {
        id: "do-3",
        name: "Large Company (KES 500M-2B revenue)",
        amount: 375000,
        period: "annually",
        description: "Up to KES 100M cover",
      },
      {
        id: "do-4",
        name: "Enterprise (2B+ revenue)",
        amount: 750000,
        period: "annually",
        description: "Custom limits available",
      },
    ],
  },
  {
    id: "public-product-liability",
    title: "Public & Product Liability",
    slug: "public-product-liability",
    category: "liability",
    shortDescription:
      "Essential cover for businesses against injury to third parties or property damage.",
    description:
      "Whether a customer slips at your premises or a product you manufactured causes harm, public and product liability insurance protects your business from the financial fallout of legal claims.",
    icon: "Scale",
    targetAudience:
      "All businesses that interact with the public or manufacture/sell products",
    popular: true,
    features: [
      "Third-party bodily injury",
      "Third-party property damage",
      "Legal defence costs",
      "Products sold anywhere in the world",
      "Tenant's liability for leased premises",
      "Contractual liability coverage",
    ],
    premium: [
      {
        id: "pl-1",
        name: "Cover up to KES 2M",
        amount: 18000,
        period: "annually",
        description: "For small retail shops, offices",
      },
      {
        id: "pl-2",
        name: "Cover up to KES 5M",
        amount: 35000,
        period: "annually",
        description: "For restaurants, small manufacturers",
      },
      {
        id: "pl-3",
        name: "Cover up to KES 10M",
        amount: 65000,
        period: "annually",
        description: "For medium businesses",
      },
      {
        id: "pl-4",
        name: "Cover up to KES 25M",
        amount: 125000,
        period: "annually",
        description: "For larger operations",
      },
      {
        id: "pl-5",
        name: "Cover up to KES 50M",
        amount: 225000,
        period: "annually",
        description: "For industrial facilities",
      },
    ],
  },
  {
    id: "professional-indemnity",
    title: "Professional Indemnity",
    slug: "professional-indemnity",
    category: "liability",
    shortDescription:
      "Protection for professionals against claims of negligence, errors, or omissions.",
    description:
      "For professionals who provide advice, designs, or services, this policy covers legal costs and damages if a client alleges your professional work caused them financial loss.",
    icon: "Stethoscope",
    targetAudience:
      "Consultants, architects, engineers, lawyers, accountants, IT professionals, medical practitioners",
    features: [
      "Negligence claims cover",
      "Breach of professional duty",
      "Loss of documents or data",
      "Defamation and libel",
      "Run-off cover for former employees",
      "Disciplinary proceeding costs",
    ],
    premium: [
      {
        id: "pi-1",
        name: "Cover up to KES 2M",
        amount: 25000,
        period: "annually",
        description: "For sole practitioners",
      },
      {
        id: "pi-2",
        name: "Cover up to KES 5M",
        amount: 55000,
        period: "annually",
        description: "For small firms (2-5 partners)",
      },
      {
        id: "pi-3",
        name: "Cover up to KES 10M",
        amount: 95000,
        period: "annually",
        description: "For medium firms",
      },
      {
        id: "pi-4",
        name: "Cover up to KES 25M",
        amount: 185000,
        period: "annually",
        description: "For large professional firms",
      },
      {
        id: "pi-5",
        name: "Cover up to KES 50M",
        amount: 325000,
        period: "annually",
        description: "For major consultancies",
      },
    ],
  },
  {
    id: "fidelity-guarantee",
    title: "Fidelity Guarantee",
    slug: "fidelity-guarantee",
    category: "liability",
    shortDescription:
      "Cover for direct financial loss from dishonest or fraudulent acts by employees.",
    description:
      "Employees in positions of trust — cashiers, accountants, managers — can cause significant financial loss. This policy indemnifies your business against theft of money, stocks, or property by employees.",
    icon: "Fingerprint",
    targetAudience:
      "Businesses handling cash, stock, or valuable assets with employee access",
    features: [
      "Employee theft of money and goods",
      "Fraudulent conversion of assets",
      "Forgery or falsification",
      "Discovery period extension",
      "Coverage for temporary staff",
      "Partner or director dishonesty",
    ],
    premium: [
      {
        id: "fg-1",
        name: "Cover up to KES 500K",
        amount: 8500,
        period: "annually",
        description: "For small retail",
      },
      {
        id: "fg-2",
        name: "Cover up to KES 1M",
        amount: 15000,
        period: "annually",
        description: "For small offices",
      },
      {
        id: "fg-3",
        name: "Cover up to KES 2.5M",
        amount: 32000,
        period: "annually",
        description: "For medium businesses",
      },
      {
        id: "fg-4",
        name: "Cover up to KES 5M",
        amount: 58000,
        period: "annually",
        description: "For larger firms",
      },
    ],
  },
  {
    id: "bankers-blanket-bond",
    title: "Bankers Blanket Bond",
    slug: "bankers-blanket-bond",
    category: "liability",
    shortDescription:
      "Comprehensive fidelity cover designed specifically for financial institutions.",
    description:
      "A specialized policy for banks and financial institutions covering losses from employee dishonesty, forgery, robbery, burglary, counterfeit currency, and computer fraud — all in one comprehensive policy.",
    icon: "Bank",
    targetAudience:
      "Banks, microfinance institutions, SACCOs, forex bureaus, financial services firms",
    features: [
      "Employee fidelity cover",
      "On-premises robbery and burglary",
      "In-transit money and securities",
      "Forgery and alteration of instruments",
      "Counterfeit currency cover",
      "Computer system fraud",
    ],
    premium: [
      {
        id: "bbb-1",
        name: "Small MFI/SACCO",
        amount: 150000,
        period: "annually",
        description: "Up to KES 10M aggregate limit",
      },
      {
        id: "bbb-2",
        name: "Medium SACCO/Bank",
        amount: 450000,
        period: "annually",
        description: "Up to KES 50M aggregate limit",
      },
      {
        id: "bbb-3",
        name: "Large Bank",
        amount: 1250000,
        period: "annually",
        description: "Up to KES 200M aggregate limit",
      },
    ],
  },
  {
    id: "bonds-guarantees",
    title: "Bonds & Guarantees",
    slug: "bonds-guarantees",
    category: "liability",
    shortDescription:
      "Surety bonds and guarantees for contract performance, tender bids, and advance payment.",
    description:
      "Guarantee your contractual obligations with surety bonds. We issue performance bonds, tender bonds, advance payment guarantees, retention bonds, and customs bonds for businesses tendering for contracts.",
    icon: "Scroll",
    targetAudience:
      "Contractors, suppliers, importers/exporters, businesses bidding for government or corporate tenders",
    features: [
      "Performance bonds",
      "Tender/bid bonds",
      "Advance payment guarantees",
      "Retention bonds",
      "Customs and excise bonds",
      "Court bonds",
    ],
    premium: [
      {
        id: "bond-1",
        name: "Tender/Bid Bond",
        amount: 2500,
        period: "one-time",
        description: "Flat fee plus 0.5% of bond value (min KES 2,500)",
      },
      {
        id: "bond-2",
        name: "Performance Bond",
        amount: 1.5,
        period: "annually",
        description: "1.5% of bond value per year",
      },
      {
        id: "bond-3",
        name: "Advance Payment Guarantee",
        amount: 2.0,
        period: "annually",
        description: "2% of guarantee value per year",
      },
      {
        id: "bond-4",
        name: "Customs Bond",
        amount: 25000,
        period: "annually",
        description: "Annual premium for regular importers",
      },
    ],
  },
];

export const PROPERTY_PRODUCTS: InsuranceService[] = [
  {
    id: "fire-burglary",
    title: "Fire & Burglary",
    slug: "fire-burglary",
    category: "property",
    shortDescription:
      "Comprehensive protection for buildings, contents, and stock against fire, theft, and related perils.",
    description:
      "Protect your physical assets from fire, lightning, explosion, riot, strike, malicious damage, and burglary. This policy covers buildings, machinery, stock, furniture, and other contents.",
    icon: "Flame",
    targetAudience:
      "Property owners, tenants, retailers, manufacturers, offices, warehouses",
    popular: true,
    features: [
      "Fire, lightning, explosion cover",
      "Riot, strike, civil commotion",
      "Malicious damage",
      "Burglary and housebreaking",
      "Impact by vehicles or falling trees",
      "Sprinkler leakage",
      "Earthquake and volcanic eruption",
    ],
    premium: [
      {
        id: "fire-1",
        name: "Home Contents - KES 1M",
        amount: 8500,
        period: "annually",
        description: "For household contents",
      },
      {
        id: "fire-2",
        name: "Building - KES 5M",
        amount: 15000,
        period: "annually",
        description: "For residential building",
      },
      {
        id: "fire-3",
        name: "Commercial Property - KES 10M",
        amount: 35000,
        period: "annually",
        description: "Office or retail space",
      },
      {
        id: "fire-4",
        name: "Industrial/Warehouse - KES 50M",
        amount: 125000,
        period: "annually",
        description: "For manufacturing or storage",
      },
      {
        id: "fire-5",
        name: "Stock/Goods - KES 20M",
        amount: 55000,
        period: "annually",
        description: "For inventory cover",
      },
    ],
  },
  {
    id: "business-interruption",
    title: "Business Interruption",
    slug: "business-interruption",
    category: "property",
    shortDescription:
      "Replace lost income and cover ongoing expenses after a covered property loss.",
    description:
      "When a fire or other insured event forces you to close, business interruption insurance replaces lost profits and pays for ongoing expenses like rent, salaries, and loan payments while you get back on your feet.",
    icon: "LineChart",
    targetAudience: "Businesses that couldn't survive a prolonged closure",
    features: [
      "Loss of gross profit",
      "Increased cost of working",
      "Rent and mortgage payments",
      "Employee wages during closure",
      "Loan repayment cover",
      "Professional accountant fees",
      "Extended indemnity period",
    ],
    premium: [
      {
        id: "bi-1",
        name: "Small Business - KES 2M annual profit",
        amount: 25000,
        period: "annually",
        description: "Add-on to fire policy",
      },
      {
        id: "bi-2",
        name: "Medium Business - KES 10M annual profit",
        amount: 95000,
        period: "annually",
        description: "12 months indemnity",
      },
      {
        id: "bi-3",
        name: "Large Business - KES 50M annual profit",
        amount: 375000,
        period: "annually",
        description: "24 months indemnity option",
      },
    ],
  },
  {
    id: "machine-breakdown",
    title: "Machine Breakdown",
    slug: "machine-breakdown",
    category: "property",
    shortDescription:
      "Cover for sudden and unforeseen damage to machinery and plant equipment.",
    description:
      "Boilers, pressure vessels, air conditioners, production machinery, and electrical equipment can fail catastrophically. This policy covers repair or replacement costs when breakdown occurs from mechanical or electrical faults.",
    icon: "Cog",
    targetAudience:
      "Manufacturing plants, hotels, hospitals, factories, industrial facilities",
    features: [
      "Mechanical breakdown cover",
      "Electrical malfunction cover",
      "Repair and replacement costs",
      "Express freight for parts",
      "Overtime labour costs",
      "Undamaged surrounding property",
      "Statutory inspection costs",
    ],
    premium: [
      {
        id: "mb-1",
        name: "Equipment value up to KES 2M",
        amount: 15000,
        period: "annually",
        description: "For small machinery",
      },
      {
        id: "mb-2",
        name: "Equipment value up to KES 10M",
        amount: 55000,
        period: "annually",
        description: "For medium plant",
      },
      {
        id: "mb-3",
        name: "Equipment value up to KES 50M",
        amount: 225000,
        period: "annually",
        description: "For industrial equipment",
      },
    ],
  },
  {
    id: "electronic-equipment",
    title: "Electronic Equipment",
    slug: "electronic-equipment",
    category: "property",
    shortDescription:
      "All-risks cover for computers, servers, medical equipment, and sensitive electronics.",
    description:
      "Protect your valuable electronic equipment against breakdown, accidental damage, power surges, and theft. Ideal for computers, servers, medical diagnostic equipment, CCTV systems, and more.",
    icon: "Cpu",
    targetAudience:
      "IT companies, hospitals, banks, media houses, offices with expensive electronics",
    features: [
      "Accidental damage cover",
      "Electrical and mechanical breakdown",
      "Power surge and fluctuation",
      "Theft of equipment",
      "On-site and off-site cover",
      "Data restoration costs",
      "Express repair or replacement",
    ],
    premium: [
      {
        id: "ee-1",
        name: "Equipment value up to KES 500K",
        amount: 7500,
        period: "annually",
        description: "For basic office computers",
      },
      {
        id: "ee-2",
        name: "Equipment value up to KES 2M",
        amount: 25000,
        period: "annually",
        description: "For small server room",
      },
      {
        id: "ee-3",
        name: "Equipment value up to KES 10M",
        amount: 95000,
        period: "annually",
        description: "For data centre or hospital equipment",
      },
    ],
  },
  {
    id: "goods-in-transit",
    title: "Goods in Transit",
    slug: "goods-in-transit",
    category: "property",
    shortDescription:
      "Protection for goods while being transported by road, rail, air, or sea.",
    description:
      "Whether you own a delivery vehicle or use third-party transporters, goods in transit insurance covers loss or damage to your cargo during transportation — from theft to accidents to spoilage.",
    icon: "Truck",
    targetAudience:
      "Distributors, wholesalers, manufacturers, retailers, logistics companies",
    features: [
      "Loss or damage during transit",
      "Theft of entire vehicle",
      "Pilferage cover",
      "Refrigerated goods spoilage",
      "Own vehicle and hired transport",
      "Loading and unloading cover",
      "Consequential loss extension",
    ],
    premium: [
      {
        id: "git-1",
        name: "Goods value up to KES 1M per trip",
        amount: 15000,
        period: "annually",
        description: "For small deliveries",
      },
      {
        id: "git-2",
        name: "Goods value up to KES 5M per trip",
        amount: 55000,
        period: "annually",
        description: "For regular distribution",
      },
      {
        id: "git-3",
        name: "Goods value up to KES 20M per trip",
        amount: 185000,
        period: "annually",
        description: "For large cargo operations",
      },
      {
        id: "git-4",
        name: "Per trip cover",
        amount: 0.75,
        period: "one-time",
        description: "0.75% of cargo value - minimum KES 5,000",
      },
    ],
  },
  {
    id: "political-violence",
    title: "Political Violence & Terrorism",
    slug: "political-violence",
    category: "property",
    shortDescription:
      "Cover for damage from strikes, riots, civil commotion, terrorism, and sabotage.",
    description:
      "In Kenya's dynamic environment, this policy provides essential coverage for property damage or business interruption caused by political violence events excluded from standard fire policies.",
    icon: "AlertTriangle",
    targetAudience:
      "Hotels, retail centres, offices, factories, diplomatic missions, NGOs",
    features: [
      "Strike, riot, civil commotion",
      "Terrorism and sabotage",
      "Malicious damage",
      "Business interruption extension",
      "Evacuation costs",
      "Security expenses",
    ],
    premium: [
      {
        id: "pv-1",
        name: "Property value up to KES 10M",
        amount: 25000,
        period: "annually",
        description: "For small businesses",
      },
      {
        id: "pv-2",
        name: "Property value up to KES 50M",
        amount: 95000,
        period: "annually",
        description: "For medium enterprises",
      },
      {
        id: "pv-3",
        name: "Property value up to KES 200M",
        amount: 325000,
        period: "annually",
        description: "For large hotels or malls",
      },
    ],
  },
  {
    id: "marine",
    title: "Marine Insurance",
    slug: "marine",
    category: "property",
    shortDescription:
      "Complete cargo and hull coverage for importers, exporters, and shipping companies.",
    description:
      "Protect your cargo throughout its journey — from port of origin to final destination. We cover all major modes of transportation including sea, air, and road. Open cover policies available for regular shippers.",
    icon: "Ship",
    targetAudience:
      "Importers, exporters, freight forwarders, shipping lines, logistics companies",
    popular: true,
    features: [
      "Cargo all-risks cover",
      "Open cover policies",
      "Single shipment policies",
      "War and strike risks extension",
      "Containers cover",
      "Hull and machinery",
      "General average contributions",
    ],
    premium: [
      {
        id: "marine-1",
        name: "Single Shipment - Small",
        amount: 7500,
        period: "one-time",
        description: "For cargo value up to KES 1M",
      },
      {
        id: "marine-2",
        name: "Single Shipment - Medium",
        amount: 25000,
        period: "one-time",
        description: "For cargo value up to KES 5M",
      },
      {
        id: "marine-3",
        name: "Open Cover - Small importer",
        amount: 150000,
        period: "annually",
        description: "Up to KES 20M annual turnover",
      },
      {
        id: "marine-4",
        name: "Open Cover - Medium importer",
        amount: 450000,
        period: "annually",
        description: "Up to KES 100M annual turnover",
      },
      {
        id: "marine-5",
        name: "Open Cover - Large importer",
        amount: 1250000,
        period: "annually",
        description: "Up to KES 500M annual turnover",
      },
    ],
  },
];

export const PEOPLE_PRODUCTS: InsuranceService[] = [
  {
    id: "wiba",
    title: "Work Injury Benefits Act (WIBA)",
    slug: "wiba",
    category: "people",
    shortDescription:
      "Statutory cover for workplace injuries — mandatory for all Kenyan employers.",
    description:
      "WIBA is a compulsory statutory insurance for all employers in Kenya. It provides benefits to employees who suffer occupational injuries or diseases, including medical expenses, disability benefits, and death benefits.",
    icon: "Briefcase",
    targetAudience: "All employers in Kenya (legal requirement)",
    popular: true,
    features: [
      "Medical expenses for work injuries",
      "Temporary and permanent disability benefits",
      "Death benefits to dependants",
      "Funeral expenses",
      "Cover for occupational diseases",
      "No-fault compensation system",
      "Compliance with Kenyan law",
    ],
    premium: [
      {
        id: "wiba-1",
        name: "1-5 employees",
        amount: 12000,
        period: "annually",
        description: "Based on payroll",
      },
      {
        id: "wiba-2",
        name: "6-20 employees",
        amount: 35000,
        period: "annually",
        description: "Based on payroll",
      },
      {
        id: "wiba-3",
        name: "21-50 employees",
        amount: 75000,
        period: "annually",
        description: "Based on payroll",
      },
      {
        id: "wiba-4",
        name: "51-100 employees",
        amount: 145000,
        period: "annually",
        description: "Based on payroll",
      },
      {
        id: "wiba-5",
        name: "100+ employees",
        amount: 0.6,
        period: "annually",
        description: "0.6% of annual payroll - custom quote",
      },
    ],
  },
  {
    id: "medical",
    title: "Medical Insurance",
    slug: "medical",
    category: "people",
    shortDescription:
      "Comprehensive health cover for employees — inpatient, outpatient, maternity, dental.",
    description:
      "Corporate medical plans designed for Kenyan businesses. Access to leading hospitals, flexible benefit limits, and customizable options including inpatient, outpatient, maternity, dental, optical, and last expense.",
    icon: "HeartPulse",
    targetAudience:
      "Businesses seeking health benefits for employees and their families",
    popular: true,
    features: [
      "Inpatient and outpatient cover",
      "Maternity benefits",
      "Dental and optical",
      "Last expense cover",
      "Pre-existing conditions after waiting period",
      "International emergency evacuation",
      "Hospital cash benefit",
    ],
    premium: [
      {
        id: "medical-1",
        name: "Individual Staff - Inpatient only",
        amount: 12500,
        period: "annually",
        description: "Basic inpatient cover",
      },
      {
        id: "medical-2",
        name: "Individual Staff - Comprehensive",
        amount: 25000,
        period: "annually",
        description: "Inpatient + Outpatient + Maternity",
      },
      {
        id: "medical-3",
        name: "Family (Member + Spouse + 2 children)",
        amount: 65000,
        period: "annually",
        description: "Full family cover",
      },
      {
        id: "medical-4",
        name: "Group (10+ staff) - per person",
        amount: 18500,
        period: "annually",
        description: "Discounted group rate",
      },
    ],
  },
  {
    id: "group-life",
    title: "Group Life Insurance",
    slug: "group-life",
    category: "people",
    shortDescription:
      "Employee life and disability cover — builds loyalty and protects families.",
    description:
      "Provide peace of mind to your employees with group life insurance covering death, permanent disability, and critical illness. Optional cover for spouses and children available.",
    icon: "Users",
    targetAudience:
      "Companies of all sizes, especially registered group schemes",
    popular: true,
    features: [
      "Death benefit (multiple of salary)",
      "Permanent total disability cover",
      "Critical illness extension",
      "Spouse and children cover",
      "Funeral expenses",
      "Premium waiver on disability",
      "24-hour worldwide cover",
    ],
    premium: [
      {
        id: "gl-1",
        name: "Basic - 1x annual salary",
        amount: 2500,
        period: "annually",
        description: "Per employee",
      },
      {
        id: "gl-2",
        name: "Standard - 2x annual salary",
        amount: 4500,
        period: "annually",
        description: "Per employee",
      },
      {
        id: "gl-3",
        name: "Enhanced - 3x annual salary",
        amount: 6500,
        period: "annually",
        description: "Per employee",
      },
      {
        id: "gl-4",
        name: "Premium - 4x annual salary",
        amount: 8500,
        period: "annually",
        description: "Per employee",
      },
      {
        id: "gl-5",
        name: "Plus Critical Illness",
        amount: 1250,
        period: "annually",
        description: "Add-on per employee",
      },
    ],
  },
  {
    id: "personal-accident-people",
    title: "Personal Accident (Group)",
    slug: "personal-accident-group",
    category: "people",
    shortDescription:
      "24-hour accident protection for employees, on or off the job.",
    description:
      "Provides lump-sum benefits for employees who suffer accidental death or permanent disablement — whether at work, commuting, or during leisure activities. Flexible benefit tables available.",
    icon: "Shield",
    targetAudience:
      "Companies wanting to enhance employee benefits beyond WIBA",
    features: [
      "Accidental death benefit",
      "Permanent total disablement",
      "Permanent partial disablement",
      "Temporary total disablement (weekly benefit)",
      "Medical expenses for accidents",
      "Funeral expenses",
      "Family member cover extension",
    ],
    premium: [
      {
        id: "pa-1",
        name: "Basic - KES 500K cover",
        amount: 1250,
        period: "annually",
        description: "Per employee",
      },
      {
        id: "pa-2",
        name: "Standard - KES 1M cover",
        amount: 2250,
        period: "annually",
        description: "Per employee",
      },
      {
        id: "pa-3",
        name: "Enhanced - KES 2M cover",
        amount: 4000,
        period: "annually",
        description: "Per employee",
      },
      {
        id: "pa-4",
        name: "Premium - KES 5M cover",
        amount: 9000,
        period: "annually",
        description: "Per employee",
      },
    ],
  },
];

export const PERSONAL_PRODUCTS: InsuranceService[] = [
  {
    id: "domestic-package",
    title: "Domestic Package",
    slug: "domestic-package",
    category: "personal",
    shortDescription:
      "All-in-one home insurance — buildings, contents, valuables, and liability.",
    description:
      "A bundled policy for homeowners and tenants covering your home building, contents, personal valuables, and even domestic workers under one convenient package.",
    icon: "Home",
    targetAudience: "Homeowners and tenants",
    popular: true,
    features: [
      "Building structure cover",
      "Contents and personal effects",
      "Valuables and jewellery",
      "All-risks cover on specified items",
      "Refrigerated food spoilage",
      "Domestic worker WIBA cover",
      "Personal liability protection",
    ],
    premium: [
      {
        id: "dp-1",
        name: "Tenant Package",
        amount: 6500,
        period: "annually",
        description: "Contents up to KES 500K",
      },
      {
        id: "dp-2",
        name: "Homeowner Basic",
        amount: 12500,
        period: "annually",
        description: "Building KES 3M + Contents KES 1M",
      },
      {
        id: "dp-3",
        name: "Homeowner Plus",
        amount: 22500,
        period: "annually",
        description: "Building KES 6M + Contents KES 2.5M",
      },
      {
        id: "dp-4",
        name: "Homeowner Premium",
        amount: 38500,
        period: "annually",
        description: "Building KES 10M + Contents KES 5M",
      },
    ],
  },
  {
    id: "motor-private",
    title: "Motor Insurance — Private",
    slug: "motor-private",
    category: "personal",
    shortDescription:
      "Comprehensive cover for private vehicles with no-claims bonus and 24/7 assistance.",
    description:
      "Protect your private vehicle against accident, theft, fire, and third-party liability. Options include comprehensive, third-party plus fire & theft, or basic third-party.",
    icon: "Car",
    targetAudience: "Individual car owners",
    popular: true,
    features: [
      "Comprehensive or third-party options",
      "24/7 roadside assistance",
      "Windscreen cover",
      "No-claims bonus protection",
      "Personal accident cover for driver",
      "Passenger liability",
      "Courtesy car option",
    ],
    premium: [
      {
        id: "motor-p1",
        name: "Third Party Only",
        amount: 5500,
        period: "annually",
        description: "Basic legal requirement",
      },
      {
        id: "motor-p2",
        name: "Third Party + Fire & Theft",
        amount: 12500,
        period: "annually",
        description: "For older vehicles (1000-1300cc)",
      },
      {
        id: "motor-p3",
        name: "Comprehensive - Small car (1300cc)",
        amount: 25000,
        period: "annually",
        description: "For vehicles like Toyota Vitz, Suzuki",
      },
      {
        id: "motor-p4",
        name: "Comprehensive - Medium car (1500-1800cc)",
        amount: 35000,
        period: "annually",
        description: "For Toyota Axio, Premio, Honda Fit",
      },
      {
        id: "motor-p5",
        name: "Comprehensive - Large car (1800cc+)",
        amount: 55000,
        period: "annually",
        description: "For SUVs, Luxury sedans",
      },
    ],
  },
  {
    id: "motor-commercial",
    title: "Motor Insurance — Commercial",
    slug: "motor-commercial",
    category: "personal",
    shortDescription: "Fleet and commercial vehicle cover for businesses.",
    description:
      "Designed for business-owned vehicles including pickup trucks, vans, lorries, and utility vehicles. Fleet discounts available for 5+ vehicles.",
    icon: "Truck",
    targetAudience: "Businesses with commercial vehicle fleets",
    features: [
      "Comprehensive or third-party cover",
      "Fleet policy discounts",
      "Goods-in-transit extension",
      "Driver and conductor accident cover",
      "Off-road cover for construction vehicles",
      "Loader liability",
      "Nairobi Expressway cover",
    ],
    premium: [
      {
        id: "motor-c1",
        name: "Pickup/LDV (3rd Party)",
        amount: 8500,
        period: "annually",
        description: "For Isuzu, Toyota Hilux",
      },
      {
        id: "motor-c2",
        name: "Pickup/LDV (Comprehensive)",
        amount: 45000,
        period: "annually",
        description: "Full cover for commercial use",
      },
      {
        id: "motor-c3",
        name: "Lorry/Truck (5-10 ton)",
        amount: 65000,
        period: "annually",
        description: "Comprehensive cover",
      },
      {
        id: "motor-c4",
        name: "Fleet Discount (5+ vehicles)",
        amount: 0,
        period: "annually",
        description: "10-20% discount - custom quote",
      },
    ],
  },
  {
    id: "motor-psv",
    title: "Motor Insurance — PSV",
    slug: "motor-psv",
    category: "personal",
    shortDescription:
      "Specialized cover for public service vehicles — matatus, buses, taxis.",
    description:
      "Tailored for matatus, buses, taxis, and other PSVs. Covers vehicle damage, passenger liability, and complies with NTSA requirements.",
    icon: "Bus",
    targetAudience: "PSV owners, SACCOS, transport companies",
    features: [
      "Vehicle damage cover",
      "Passenger legal liability",
      "Conductor and driver cover",
      "Third-party liability",
      "Crew personal accident",
      "Loss of revenue extension",
      "Compliance with NTSA regulations",
    ],
    premium: [
      {
        id: "psv-1",
        name: "Matatu (14-seater)",
        amount: 65000,
        period: "annually",
        description: "Comprehensive + Passenger liability",
      },
      {
        id: "psv-2",
        name: "Bus (30-40 seater)",
        amount: 125000,
        period: "annually",
        description: "Comprehensive + Passenger liability",
      },
      {
        id: "psv-3",
        name: "Bus (50+ seater)",
        amount: 185000,
        period: "annually",
        description: "Comprehensive + Passenger liability",
      },
      {
        id: "psv-4",
        name: "Taxi/Cab",
        amount: 35000,
        period: "annually",
        description: "Comprehensive cover",
      },
      {
        id: "psv-5",
        name: "Uber/Bolt",
        amount: 40000,
        period: "annually",
        description: "Comprehensive + Rideshare extension",
      },
    ],
  },
  {
    id: "motor-cycle",
    title: "Motor Cycle Insurance",
    slug: "motor-cycle",
    category: "personal",
    shortDescription: "Affordable cover for boda boda and private motorcycles.",
    description:
      "Designed for motorcycle owners including boda boda operators and private riders. Comprehensive or third-party options available.",
    icon: "Bike",
    targetAudience: "Motorcycle owners, boda boda operators",
    features: [
      "Comprehensive or third-party cover",
      "Rider personal accident",
      "Passenger liability for boda boda",
      "Theft of motorcycle",
      "Fire and vandalism cover",
      "Third-party property damage",
    ],
    premium: [
      {
        id: "bike-1",
        name: "Third Party Only",
        amount: 2500,
        period: "annually",
        description: "For Boxer, Jinbei (125cc)",
      },
      {
        id: "bike-2",
        name: "Comprehensive - Small bike",
        amount: 7500,
        period: "annually",
        description: "Up to 200cc",
      },
      {
        id: "bike-3",
        name: "Comprehensive - Large bike",
        amount: 12500,
        period: "annually",
        description: "Above 200cc",
      },
      {
        id: "bike-4",
        name: "Boda Boda Special",
        amount: 9500,
        period: "annually",
        description: "Comprehensive + Passenger liability",
      },
    ],
  },
  {
    id: "personal-accident",
    title: "Personal Accident (Individual)",
    slug: "personal-accident",
    category: "personal",
    shortDescription:
      "24-hour accident protection for individuals and families.",
    description:
      "Provides lump-sum benefits for accidental death, permanent disablement, and medical expenses. A simple, affordable way to add accident protection.",
    icon: "User",
    targetAudience: "Individuals without group cover",
    features: [
      "Accidental death benefit",
      "Permanent total/partial disablement",
      "Temporary disablement benefit",
      "Medical expenses after accident",
      "Funeral expenses",
      "Family cover options",
      "24-hour worldwide cover",
    ],
    premium: [
      {
        id: "pa-ind-1",
        name: "Individual - KES 500K cover",
        amount: 2500,
        period: "annually",
        description: "Basic accident cover",
      },
      {
        id: "pa-ind-2",
        name: "Individual - KES 1M cover",
        amount: 4500,
        period: "annually",
        description: "Standard cover",
      },
      {
        id: "pa-ind-3",
        name: "Family Package (2 adults + children)",
        amount: 8500,
        period: "annually",
        description: "KES 1M per adult",
      },
      {
        id: "pa-ind-4",
        name: "Senior Citizen (60+)",
        amount: 6500,
        period: "annually",
        description: "KES 1M cover",
      },
    ],
  },
  {
    id: "medical-personal",
    title: "Medical Cover (Individual/Family)",
    slug: "medical-personal",
    category: "personal",
    shortDescription:
      "Individual and family health plans with access to top hospitals.",
    description:
      "Health insurance for individuals, families, and senior citizens. Choose from inpatient-only or comprehensive outpatient plans.",
    icon: "HeartPulse",
    targetAudience: "Individuals and families without employer medical cover",
    features: [
      "Inpatient cover",
      "Outpatient benefits (optional)",
      "Maternity cover",
      "Dental and optical",
      "Last expense",
      "Hospital network access",
      "Pre-existing condition assessment",
    ],
    premium: [
      {
        id: "med-per-1",
        name: "Individual - Inpatient only",
        amount: 15000,
        period: "annually",
        description: "KES 500K limit",
      },
      {
        id: "med-per-2",
        name: "Individual - Comprehensive",
        amount: 35000,
        period: "annually",
        description: "KES 1M limit + Outpatient",
      },
      {
        id: "med-per-3",
        name: "Couple - Comprehensive",
        amount: 65000,
        period: "annually",
        description: "For married couple",
      },
      {
        id: "med-per-4",
        name: "Family (2 adults + 2 children)",
        amount: 95000,
        period: "annually",
        description: "Full family cover",
      },
      {
        id: "med-per-5",
        name: "Single Parent + 2 children",
        amount: 65000,
        period: "annually",
        description: "Alternative family plan",
      },
    ],
  },
  {
    id: "travel",
    title: "Travel Insurance",
    slug: "travel",
    category: "personal",
    shortDescription:
      "Comprehensive travel protection for domestic and international trips.",
    description:
      "Don't let unexpected events ruin your travels. Covers medical emergencies abroad, trip cancellations, lost luggage, flight delays, and personal liability.",
    icon: "Plane",
    targetAudience: "Leisure and business travellers",
    popular: true,
    features: [
      "Medical emergency abroad",
      "Trip cancellation cover",
      "Lost baggage and documents",
      "Flight delay compensation",
      "Personal liability",
      "Adventure sports add-on",
      "Single or multi-trip policies",
    ],
    premium: [
      {
        id: "travel-1",
        name: "Single Trip - Regional (EAC)",
        amount: 2500,
        period: "one-time",
        description: "Up to 14 days, medical KES 5M",
      },
      {
        id: "travel-2",
        name: "Single Trip - International",
        amount: 6500,
        period: "one-time",
        description: "Up to 30 days",
      },
      {
        id: "travel-3",
        name: "Single Trip - Worldwide including USA",
        amount: 9500,
        period: "one-time",
        description: "USA/Canada cover",
      },
      {
        id: "travel-4",
        name: "Annual Multi-Trip",
        amount: 25000,
        period: "annually",
        description: "Unlimited trips, 45 days max per trip",
      },
      {
        id: "travel-5",
        name: "Schengen Visa Compliant",
        amount: 4500,
        period: "one-time",
        description: "€30,000 minimum cover",
      },
    ],
  },
];

// Combined export for all products
export const ALL_PRODUCTS: InsuranceService[] = [
  ...LIABILITY_PRODUCTS,
  ...PROPERTY_PRODUCTS,
  ...PEOPLE_PRODUCTS,
  ...PERSONAL_PRODUCTS,
];

// Helper function to get product by ID
export function getProductById(id: string): InsuranceService | undefined {
  return ALL_PRODUCTS.find((product) => product.id === id);
}

// Helper function to get products by class
export function getProductsByCategory(className: string): InsuranceService[] {
  return ALL_PRODUCTS.filter((product) => product.category === className);
}
